spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      replication-factor: ${KAFKA_REPLICATION_FACTOR}
      num-partition: ${KAFKA_NUM_PARTITION}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: true
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        specific.avro.reader: true
  datasource:
    url: ${POSTGRE_DATABASE_URL}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: ${POSTGRE_MAXIMUM_POOL_SIZE}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  batch:
    initialize-schema: always
logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.cmcglobal.kafkstreamprocessor: ${LOG_LEVEL}
debug: ${DEBUG}
