spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      replication-factor: ${KAFKA_REPLICATION_FACTOR}
      num-partition: ${KAFKA_NUM_PARTITION}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: true
      properties:
        schema.registry.url: ${KAFKA_REGISTRY_URL}
        specific.avro.reader: true
logging:
  level:
    org.springframework: ${LOG_LEVEL}
    com.cmcglobal.kafkstreamprocessor: ${LOG_LEVEL}
debug: ${DEBUG}
